language: node_js
node_js:
  - "stable"
  - "8"
  - "9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script: npm run test:ci
